/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useEffect } from "react";

export default function Model(props) {
    const group = useRef();
    const { nodes, materials, animations } = useGLTF("/human/mixamo.glb");
    const { actions } = useAnimations(animations, group);
    console.log(actions)

    useEffect(() => {
        // const action = animations.actions['HG_Elliot|WalkCycleAction']
        const action = actions['sitting_cry']
        action.play()
    }, [])

    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Scene">
                <group name="Armature" rotation={[Math.PI / 2, 0, 0]}>
                    <skinnedMesh
                        name="HG_Body"
                        geometry={nodes.HG_Body.geometry}
                        material={materials["Material.001"]}
                        skeleton={nodes.HG_Body.skeleton}
                    />
                    <skinnedMesh
                        name="HG_Eyes"
                        geometry={nodes.HG_Eyes.geometry}
                        material={materials["Material.002"]}
                        skeleton={nodes.HG_Eyes.skeleton}
                    />
                    <skinnedMesh
                        name="HG_TeethLower"
                        geometry={nodes.HG_TeethLower.geometry}
                        material={nodes.HG_TeethLower.material}
                        skeleton={nodes.HG_TeethLower.skeleton}
                    />
                    <skinnedMesh
                        name="HG_TeethUpper"
                        geometry={nodes.HG_TeethUpper.geometry}
                        material={nodes.HG_TeethUpper.material}
                        skeleton={nodes.HG_TeethUpper.skeleton}
                    />
                    <primitive object={nodes.mixamorigHips} />
                </group>
            </group>
        </group>
    );
}

useGLTF.preload("/human/mixamo.glb");